### PR TITLE
Add appid to name of desktop, appdata and icon

### PR DESCRIPTION
**Pull request by cpba**
This way it conforms to freedesktop standards and we don't need to
rename files in flatpak-builder. I tested it like this and it seems to work,
I think I got every reference to the files but there may be something that I missed.

### CODE REVIEW

**Comment by cpba** [comment]
I knew I had to be missing something! ;)

It didn't fail during testing because I had also forgotten about removing the old icon

**Comment by SilverRainZ** [comment]
There is three version of app icon: `srain`, `srain-red` and `srain-black`, it is strange that rename the first one and left the other tow icon not changed... Again, could you please find the spec about icon naming for app icon and non-app icon?

**Comment by cpba** [comment]
I didn't say anything because all I could find is this:
https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

I'll keep looking but it's likely that it doesn't exist, the freedesktop specs are meant to make interoperation easier between different desktop environments, they care about the part that concerns the standard icons and the part that concerns the desktop file, but once your application has launched, I think that's left undefined.

**Comment by SilverRainZ** [comment]
@TingPing Do you know any thing about this?

**Comment by cpba** [comment]
@SilverRainZ I added an extra commit with the reference, tested locally and it seems to work.

**Comment by TingPing** [comment]
> There is three version of app icon: srain, srain-red and srain-black, it is strange that rename the first one and left the other tow icon not changed...

If they are private icons the name doesn't matter, in that case they honestly should not even be installed and just be kept in GResources. You can name them `im.srain.Srain-red` or such also.

@SilverRainZ The icon theme spec doesn't have any recommendations for naming if that is what you are asking.

**Comment by SilverRainZ** [comment]
@TingPing Thanks for explanation, I will let all private icon to be managed by GResources.

**Pull request merged**
